/*
 * MSP_init.c
 *
 *  Created on: Oct 19, 2015
 *      Author: cgoss
 */

#include"MSP430.h"
#include"CC110l.h"
#include"SPI_Library.h"
#include"SPI_Pins.h"
#include "sleep_timer.h"

/*--------------------------------------------- Value Line ---------------------- */
#ifdef __MSP430G2553__

void Board_Init()
{
	WDTCTL = WDTPW | WDTHOLD;	// Stop watchdog timer

	// Clock setup
	DCOCTL = CALDCO_1MHZ;
	BCSCTL1 = CALBC1_1MHZ;
	BCSCTL2 = SELM_0; // Source MCLK and SMCLK from DCO
	BCSCTL3 = XCAP_3; // 32768 crystal, internal load caps at 12.5pF

	// Default pinsets for low power consumption

	// Set the default output to low
	P1OUT = 0;
	P2OUT = 0;
	P3OUT = 0;

	// Set the direction to out
	P1DIR = 0xFF;
	P2DIR = 0xFF;
	P3DIR = 0XFF;

//	P1DIR |= BIT0; // Configure LED 1 for output
//	P1DIR |= BIT6; // Configure LED 2 for output

	_EINT();
}

void Timer_Init()
{
	// Timer A0 init
	TA0R = 0;	// Start at 0
	TA0CCR0 = 65535; // Count up to max value
	TA0CTL |= TASSEL_1; // TA clock source is ACLK, input divider 1
	TA0CTL &= ~(TAIFG);
	TA0CTL |= TAIE;
	TA0CTL |= MC_2; // enable TA in continuous mode
}
#endif



void Radio_Init()
{
	SPI_Strobe(SRES, Get_RX_FIFO); // Reset radio

	Sleep_Timer(0,40);

	//
	// Rf settings for CC110L, generated by SmartRF Studio
	// This is the very bottom option on the dropdown list
	// 250 kBaud, Dev.: 127 kHz, Mod.: GFSK, RX BW: 540 kHz
	SPI_Send(GDO_RX,0x2E);		 //Set GDO_RX to tri-state
	SPI_Send(PKTCTRL0,0x05);     //Packet Automation Control
	SPI_Send(PKTCTRL1,BIT2 | BIT3);	// Append RSSI and CRC and enable autoflush of bad pkts
	SPI_Send(FSCTRL1,0x12);      //Frequency Synthesizer Control
	SPI_Send(FREQ2,0x21);        //Frequency Control Word, High Byte
	SPI_Send(FREQ1,0x62);        //Frequency Control Word, Middle Byte
	SPI_Send(FREQ0,0x76);        //Frequency Control Word, Low Byte
	SPI_Send(MDMCFG4,0x2D);      //Modem Configuration
	SPI_Send(MDMCFG3,0x3B);      //Modem Configuration
	SPI_Send(MDMCFG2,0x93);      //Modem Configuration
	SPI_Send(DEVIATN,0x62);      //Modem Deviation Setting
	SPI_Send(MCSM0,0x18);        //Main Radio Control State Machine Configuration
	SPI_Send(FOCCFG,0x1D);       //Frequency Offset Compensation Configuration
	SPI_Send(BSCFG,0x1C);        //Bit Synchronization Configuration
	SPI_Send(AGCCTRL2,0xC7);     //AGC Control
	SPI_Send(AGCCTRL1,0x00);     //AGC Control
	SPI_Send(AGCCTRL0,0xB0);     //AGC Control
	SPI_Send(0x20,0xFB);		 //Use setting from SmartRF Studio
	SPI_Send(FREND1,0xB6);       //Front End RX Configuration
	SPI_Send(FSCAL3,0xEA);       //Frequency Synthesizer Calibration
	SPI_Send(FSCAL2,0x2A);       //Frequency Synthesizer Calibration
	SPI_Send(FSCAL1,0x00);       //Frequency Synthesizer Calibration
	SPI_Send(FSCAL0,0x1F);       //Frequency Synthesizer Calibration
	SPI_Send(TEST0,0x09);        //Various Test Settings
}
