.TH "Stikine Directory Reference" 3 "Mon Nov 23 2015" "Stikine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stikine Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCC110l\&.h\fP"
.br
.RI "\fIContains definitions for the registers, strobes, and bit masks for the CC110l\&. \fP"
.ti -1c
.RI "file \fBClustering\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "\fIMain control code and interrupt definitions for sensor node\&. \fP"
.ti -1c
.RI "file \fBMSP_Init\&.c\fP"
.br
.ti -1c
.RI "file \fBMSP_Init\&.h\fP"
.br
.ti -1c
.RI "file \fBpinDefs\&.h\fP"
.br
.ti -1c
.RI "file \fBRadio\&.c\fP"
.br
.ti -1c
.RI "file \fBRadio\&.h\fP"
.br
.RI "\fILibrary for transmitting using listen before talk\&. \fP"
.ti -1c
.RI "file \fBsleep_timer\&.c\fP"
.br
.ti -1c
.RI "file \fBsleep_timer\&.h\fP"
.br
.RI "\fISleep library for the MSP430\&. \fP"
.ti -1c
.RI "file \fBSPI_Library\&.c\fP"
.br
.RI "\fISetup and control library for the SPI link to the CC110l\&. \fP"
.ti -1c
.RI "file \fBSPI_Library\&.h\fP"
.br
.RI "\fILibrary for communicating with CC110l over SPI\&. \fP"
.ti -1c
.RI "file \fBSPI_Pins\&.h\fP"
.br
.ti -1c
.RI "file \fBStates\&.h\fP"
.br
.RI "\fIThe contains the enumeration of possible states for the main control loop\&. \fP"
.ti -1c
.RI "file \fBWait_For_Start\&.h\fP"
.br
.in -1c
