.TH "MSP_Init.h" 3 "Mon Nov 23 2015" "Stikine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSP_Init.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBoard_Init\fP (void)"
.br
.ti -1c
.RI "void \fBTimer_Init\fP (void)"
.br
.ti -1c
.RI "void \fBRadio_Init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Board_Init (void)"

.SS "void Radio_Init (void)"

.SS "void Timer_Init (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Stikine from the source code\&.
