.TH "pinDefs.h" 3 "Sun Nov 29 2015" "Stikine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinDefs.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTrue\fP   1"
.br
.ti -1c
.RI "#define \fBFalse\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define False   0"

.SS "#define True   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for Stikine from the source code\&.
